repos:
  # https://pycqa.github.io/isort/docs/configuration/black_compatibility.html#integration-with-pre-commit
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile", "black", "--filter-files"]
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black-jupyter
  # https://black.readthedocs.io/en/stable/guides/using_black_with_other_tools.html?highlight=other%20tools#flake8
  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        args: [--max-line-length=88, "--extend-ignore=E203,E712"]
        exclude: ^src/nectarchain/user_scripts/
  - repo: https://github.com/mwouts/jupytext
    rev: v1.14.6
    hooks:
    - id: jupytext
      args: [--from, ipynb, --to, "py:percent"]
