name: ctapipe-io-nectarcam
channels:
  - conda-forge
  - default
dependencies:
  - ctapipe=0.19
  - h5py
  - ipython
  - numba
  - numpydoc
  - pip
  - protozfits
  - pytest
  - pytest-runner
  - pyyaml
  - scipy=1.11.4
  - zeromq
  - zlib
