name: ctapipe-io-nectarcam
channels:
  - conda-forge
  - default
dependencies:
  - python=3.13
  - ctapipe=0.24
  - h5py
  - ipython
  - numba
  - numpy<2.4
  - numpydoc
  - pip
  - protozfits
  - pytest
  - pytest-runner
  - pyyaml
  - scipy
  - setuptools<81
  - zeromq
  - zlib
