channels:
  - conda-forge
  - default
dependencies:
  - astropy~=4.2
  - python=3.8 # nail the python version, so conda does not try upgrading / dowgrading
  - ctapipe=0.12
  - eventio
  - corsikaio
  - protozfits=2.0
  - zeromq
  - ipython
  - numba
  - numpy=1.22 # higher versions >=1.23 don't work due to astropy4 dependency in ctapipe0.12
  - numpydoc
  - pytest
  - pytables>=3.7
  - pyyaml
  - zlib
  - pip
  - h5py
  - pip:
      - pytest_runner
