name: nectarchain
channels:
  - default
  - conda-forge
dependencies:
  - python=3.11
  - ctapipe=0.24.0
  # - ctapipe-io-nectarcam  # TODO: should be added back when merging PR
  - jinja2
  - jupyterlab
  - jupytext
  - pre-commit
  - pytest-runner
  - pip
  - pandas
  - scipy
  - sphinx
  - sphinx-automodapi
  - pydata-sphinx-theme
  - lmfit # needed into TRR
  - h5py # needed into TRR (should be removed to use I/O methods of containers)
  - pyqt
  - pip:
    - zeo
    - zodb
    - mechanize
    - browser-cookie3
    - pyqtgraph
    - sphinx-qt-documentation
