channels:
  - conda-forge
  - default
dependencies:
  - astropy>=4.2
  - python=3.8 # nail the python version, so conda does not try upgrading / dowgrading
  - ctapipe=0.12
  - eventio
  - corsikaio
  - protozfits=2.0
  - zeromq
  - ipython
  - numba
  - numpy=1.22.4 # higher versions don't work: Maxnoe: "ctapipe 0.12 depends on astropy 4, which is incompatible with the most recent numpy release 1.23"
  - numpydoc
  - pytest
  - pyyaml
  - zlib
  - pip
  - h5py
  - pip:
      - pytest_runner
