[build-system]
requires = ["setuptools >= 64.0.3", "wheel", "setuptools_scm[toml]>=3.4"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
write_to = "src/ctapipe_io_nectarcam/_version.py"